### PR TITLE
Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by jhermsmeier**
- Replace `bufferpack` with core `Buffer` methods
- Avoid `async`'s overhead through mild restructuring

### CODE REVIEW

**Comment by jviotti** [comment]
Looks great, but instead of merging here, lets take the opportunity to move this whole to `lib/image-stream`. What do you think?

**Comment by jhermsmeier** [comment]
Considering that this is on npm and we don't seem to be the only ones using it, I'd suggest moving it into `image-stream` afterwards – if you're happy to merge this – so that others can benefit from fewer dependencies as well. What do you think?

**Comment by jviotti** [comment]
Fair enough, lets do it!

**Comment by jviotti** [comment]
Check 1.0.1

**Pull request merged**
